/* Generated by Cython 0.11.2 on Sun Aug 15 10:43:51 2010 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef Py_PYTHON_H
    #error Python headers needed to compile C extensions, please install development version of Python.
#endif
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
  #define PyDict_CheckExact(op) (Py_TYPE(op) == &PyDict_Type)
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PY_FORMAT_SIZE_T ""
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
       void *buf;
       PyObject *obj;
       Py_ssize_t len;
       Py_ssize_t itemsize;
       int readonly;
       int ndim;
       char *format;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if (PY_VERSION_HEX < 0x02060000) || (PY_MAJOR_VERSION >= 3)
  #define Py_TPFLAGS_HAVE_NEWBUFFER 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyBytes_Type
  #define PyString_CheckExact          PyBytes_CheckExact
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define PyBytes_Type                 PyString_Type
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
  #ifndef __fastcall
    #define __fastcall
  #endif
#else
  #define _USE_MATH_DEFINES
#endif
#if PY_VERSION_HEX < 0x02050000
  #define __Pyx_GetAttrString(o,n)   PyObject_GetAttrString((o),((char *)(n)))
  #define __Pyx_SetAttrString(o,n,a) PyObject_SetAttrString((o),((char *)(n)),(a))
  #define __Pyx_DelAttrString(o,n)   PyObject_DelAttrString((o),((char *)(n)))
#else
  #define __Pyx_GetAttrString(o,n)   PyObject_GetAttrString((o),(n))
  #define __Pyx_SetAttrString(o,n,a) PyObject_SetAttrString((o),(n),(a))
  #define __Pyx_DelAttrString(o,n)   PyObject_DelAttrString((o),(n))
#endif
#if PY_VERSION_HEX < 0x02050000
  #define __Pyx_NAMESTR(n) ((char *)(n))
  #define __Pyx_DOCSTR(n)  ((char *)(n))
#else
  #define __Pyx_NAMESTR(n) (n)
  #define __Pyx_DOCSTR(n)  (n)
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API___caltech_distortion
#define __PYX_USE_C99_COMPLEX defined(_Complex_I)


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; long n; char is_unicode; char intern; char is_identifier;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString          PyString_FromString
#define __Pyx_PyBytes_FromStringAndSize   PyString_FromStringAndSize
#define __Pyx_PyBytes_AsString            PyString_AsString
#else
#define __Pyx_PyBytes_FromString          PyBytes_FromString
#define __Pyx_PyBytes_FromStringAndSize   PyBytes_FromStringAndSize
#define __Pyx_PyBytes_AsString            PyBytes_AsString
#endif

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject*);
static INLINE PyObject* __Pyx_PyNumber_Int(PyObject* x);

#if !defined(T_PYSSIZET)
#if PY_VERSION_HEX < 0x02050000
#define T_PYSSIZET T_INT
#elif !defined(T_LONGLONG)
#define T_PYSSIZET \
        ((sizeof(Py_ssize_t) == sizeof(int))  ? T_INT  : \
        ((sizeof(Py_ssize_t) == sizeof(long)) ? T_LONG : -1))
#else
#define T_PYSSIZET \
        ((sizeof(Py_ssize_t) == sizeof(int))          ? T_INT      : \
        ((sizeof(Py_ssize_t) == sizeof(long))         ? T_LONG     : \
        ((sizeof(Py_ssize_t) == sizeof(PY_LONG_LONG)) ? T_LONGLONG : -1)))
#endif
#endif

#if !defined(T_SIZET)
#if !defined(T_ULONGLONG)
#define T_SIZET \
        ((sizeof(size_t) == sizeof(unsigned int))  ? T_UINT  : \
        ((sizeof(size_t) == sizeof(unsigned long)) ? T_ULONG : -1))
#else
#define T_SIZET \
        ((sizeof(size_t) == sizeof(unsigned int))          ? T_UINT      : \
        ((sizeof(size_t) == sizeof(unsigned long))         ? T_ULONG     : \
        ((sizeof(size_t) == sizeof(unsigned PY_LONG_LONG)) ? T_ULONGLONG : -1)))
#endif
#endif

static INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject*);
static INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t);
static INLINE size_t __Pyx_PyInt_AsSize_t(PyObject*);

#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))


#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;


#ifdef CYTHON_REFNANNY
typedef struct {
  void (*INCREF)(void*, PyObject*, int);
  void (*DECREF)(void*, PyObject*, int);
  void (*GOTREF)(void*, PyObject*, int);
  void (*GIVEREF)(void*, PyObject*, int);
  void* (*NewContext)(const char*, int, const char*);
  void (*FinishContext)(void**);
} __Pyx_RefnannyAPIStruct;
static __Pyx_RefnannyAPIStruct *__Pyx_Refnanny = NULL;
#define __Pyx_ImportRefcountAPI(name)   (__Pyx_RefnannyAPIStruct *) PyCObject_Import((char *)name, (char *)"RefnannyAPI")
#define __Pyx_INCREF(r) __Pyx_Refnanny->INCREF(__pyx_refchk, (PyObject *)(r), __LINE__)
#define __Pyx_DECREF(r) __Pyx_Refnanny->DECREF(__pyx_refchk, (PyObject *)(r), __LINE__)
#define __Pyx_GOTREF(r) __Pyx_Refnanny->GOTREF(__pyx_refchk, (PyObject *)(r), __LINE__)
#define __Pyx_GIVEREF(r) __Pyx_Refnanny->GIVEREF(__pyx_refchk, (PyObject *)(r), __LINE__)
#define __Pyx_XDECREF(r) if((r) == NULL) ; else __Pyx_DECREF(r)
#define __Pyx_SetupRefcountContext(name)   void* __pyx_refchk = __Pyx_Refnanny->NewContext((name), __LINE__, __FILE__)
#define __Pyx_FinishRefcountContext()   __Pyx_Refnanny->FinishContext(&__pyx_refchk)
#else
#define __Pyx_INCREF(r) Py_INCREF(r)
#define __Pyx_DECREF(r) Py_DECREF(r)
#define __Pyx_GOTREF(r)
#define __Pyx_GIVEREF(r)
#define __Pyx_XDECREF(r) Py_XDECREF(r)
#define __Pyx_SetupRefcountContext(name)
#define __Pyx_FinishRefcountContext()
#endif /* CYTHON_REFNANNY */
#define __Pyx_XGIVEREF(r) if((r) == NULL) ; else __Pyx_GIVEREF(r)
#define __Pyx_XGOTREF(r) if((r) == NULL) ; else __Pyx_GOTREF(r)

static INLINE int __Pyx_CheckKeywordStrings(PyObject *kwdict,
    const char* function_name, int kw_allowed); /*proto*/

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name, PyObject* kw_name); /*proto*/

static void __Pyx_RaiseArgtupleInvalid(const char* func_name, int exact,
    Py_ssize_t num_min, Py_ssize_t num_max, Py_ssize_t num_found); /*proto*/

static int __Pyx_ParseOptionalKeywords(PyObject *kwds, PyObject **argnames[],     PyObject *kwds2, PyObject *values[], Py_ssize_t num_pos_args,     const char* function_name); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static INLINE int __Pyx_StrEq(const char *, const char *); /*proto*/

static INLINE unsigned char __Pyx_PyInt_AsUnsignedChar(PyObject *);

static INLINE unsigned short __Pyx_PyInt_AsUnsignedShort(PyObject *);

static INLINE unsigned int __Pyx_PyInt_AsUnsignedInt(PyObject *);

static INLINE char __Pyx_PyInt_AsChar(PyObject *);

static INLINE short __Pyx_PyInt_AsShort(PyObject *);

static INLINE int __Pyx_PyInt_AsInt(PyObject *);

static INLINE signed char __Pyx_PyInt_AsSignedChar(PyObject *);

static INLINE signed short __Pyx_PyInt_AsSignedShort(PyObject *);

static INLINE signed int __Pyx_PyInt_AsSignedInt(PyObject *);

static INLINE unsigned long __Pyx_PyInt_AsUnsignedLong(PyObject *);

static INLINE unsigned PY_LONG_LONG __Pyx_PyInt_AsUnsignedLongLong(PyObject *);

static INLINE long __Pyx_PyInt_AsLong(PyObject *);

static INLINE PY_LONG_LONG __Pyx_PyInt_AsLongLong(PyObject *);

static INLINE signed long __Pyx_PyInt_AsSignedLong(PyObject *);

static INLINE signed PY_LONG_LONG __Pyx_PyInt_AsSignedLongLong(PyObject *);

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

/* Type declarations */

/* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":5
 *     return CaltechDistortion(*args,**kw)
 * 
 * cdef class CaltechDistortion:             # <<<<<<<<<<<<<<
 *     cdef readonly double fc1, fc2, cc1, cc2
 *     cdef readonly double k1, k2, p1, p2
 */

struct __pyx_obj_19_caltech_distortion_CaltechDistortion {
  PyObject_HEAD
  double fc1;
  double fc2;
  double cc1;
  double cc2;
  double k1;
  double k2;
  double p1;
  double p2;
  double alpha_c;
};
/* Module declarations from _caltech_distortion */

static PyTypeObject *__pyx_ptype_19_caltech_distortion_CaltechDistortion = 0;
#define __Pyx_MODULE_NAME "_caltech_distortion"
int __pyx_module_is_main__caltech_distortion = 0;

/* Implementation of _caltech_distortion */
static PyObject *__pyx_int_0;
static char __pyx_k___main__[] = "__main__";
static PyObject *__pyx_kp___main__;
static char __pyx_k___init__[] = "__init__";
static PyObject *__pyx_kp___init__;
static char __pyx_k___reduce__[] = "__reduce__";
static PyObject *__pyx_kp___reduce__;
static char __pyx_k_undistort[] = "undistort";
static PyObject *__pyx_kp_undistort;
static char __pyx_k_distort[] = "distort";
static PyObject *__pyx_kp_distort;
static char __pyx_k_1[] = "fc1";
static PyObject *__pyx_kp_1;
static char __pyx_k_2[] = "fc2";
static PyObject *__pyx_kp_2;
static char __pyx_k_3[] = "cc1";
static PyObject *__pyx_kp_3;
static char __pyx_k_4[] = "cc2";
static PyObject *__pyx_kp_4;
static char __pyx_k_5[] = "k1";
static PyObject *__pyx_kp_5;
static char __pyx_k_6[] = "k2";
static PyObject *__pyx_kp_6;
static char __pyx_k_7[] = "p1";
static PyObject *__pyx_kp_7;
static char __pyx_k_8[] = "p2";
static PyObject *__pyx_kp_8;
static char __pyx_k_alpha_c[] = "alpha_c";
static PyObject *__pyx_kp_alpha_c;
static char __pyx_k_x_kk[] = "x_kk";
static PyObject *__pyx_kp_x_kk;
static char __pyx_k_y_kk[] = "y_kk";
static PyObject *__pyx_kp_y_kk;
static char __pyx_k_xl[] = "xl";
static PyObject *__pyx_kp_xl;
static char __pyx_k_yl[] = "yl";
static PyObject *__pyx_kp_yl;
static char __pyx_k_9[] = "make_CaltechDistortion";
static PyObject *__pyx_kp_9;

/* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":2
 * #emacs, this is -*-Python-*- mode
 * def make_CaltechDistortion(*args,**kw):             # <<<<<<<<<<<<<<
 *     return CaltechDistortion(*args,**kw)
 * 
 */

static PyObject *__pyx_pf_19_caltech_distortion_make_CaltechDistortion(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_19_caltech_distortion_make_CaltechDistortion(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_args = 0;
  PyObject *__pyx_v_kw = 0;
  PyObject *__pyx_r = NULL;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_t_1 = NULL;
  __Pyx_SetupRefcountContext("make_CaltechDistortion");
  __pyx_self = __pyx_self;
  if (unlikely(__pyx_kwds) && unlikely(!__Pyx_CheckKeywordStrings(__pyx_kwds, "make_CaltechDistortion", 1))) return NULL;
  __pyx_v_kw = (__pyx_kwds) ? PyDict_Copy(__pyx_kwds) : PyDict_New();
  if (unlikely(!__pyx_v_kw)) return NULL;
  __Pyx_GOTREF(__pyx_v_kw);
  __Pyx_INCREF(__pyx_args);
  __pyx_v_args = __pyx_args;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":3
 * #emacs, this is -*-Python-*- mode
 * def make_CaltechDistortion(*args,**kw):
 *     return CaltechDistortion(*args,**kw)             # <<<<<<<<<<<<<<
 * 
 * cdef class CaltechDistortion:
 */
  __Pyx_XDECREF(__pyx_r);
  __pyx_1 = PySequence_Tuple(__pyx_v_args); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(((PyObject *)__pyx_1));
  __pyx_t_1 = PyEval_CallObjectWithKeywords(((PyObject *)((PyObject*)__pyx_ptype_19_caltech_distortion_CaltechDistortion)), ((PyObject *)__pyx_1), __pyx_v_kw); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_1);
  __Pyx_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __pyx_r = __pyx_t_1;
  __pyx_t_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_1);
  __Pyx_XDECREF(__pyx_t_1);
  __Pyx_AddTraceback("_caltech_distortion.make_CaltechDistortion");
  __pyx_r = NULL;
  __pyx_L0:;
  __Pyx_DECREF(__pyx_v_args);
  __Pyx_DECREF(__pyx_v_kw);
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_FinishRefcountContext();
  return __pyx_r;
}

/* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":10
 *     cdef readonly double alpha_c
 * 
 *     def __init__(self, fc1, fc2, cc1, cc2, k1, k2, p1, p2, alpha_c=0 ):             # <<<<<<<<<<<<<<
 *         """create instance of CaltechDistortion
 * 
 */

static int __pyx_pf_19_caltech_distortion_17CaltechDistortion___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_19_caltech_distortion_17CaltechDistortion___init__[] = "create instance of CaltechDistortion\n\n        CaltechDistortion(fc1, fc2, cc1, cc2, k1, k2, p1, p2 )\n        where:\n        fc - focal length\n        cc - camera center\n        k - radial distortion parameters (non-linear)\n        p - tangential distortion parameters (non-linear)\n        alpha_c - skew between X and Y pixel axes\n        ";
static int __pyx_pf_19_caltech_distortion_17CaltechDistortion___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_fc1 = 0;
  PyObject *__pyx_v_fc2 = 0;
  PyObject *__pyx_v_cc1 = 0;
  PyObject *__pyx_v_cc2 = 0;
  PyObject *__pyx_v_k1 = 0;
  PyObject *__pyx_v_k2 = 0;
  PyObject *__pyx_v_p1 = 0;
  PyObject *__pyx_v_p2 = 0;
  PyObject *__pyx_v_alpha_c = 0;
  int __pyx_r;
  double __pyx_t_1;
  static PyObject **__pyx_pyargnames[] = {&__pyx_kp_1,&__pyx_kp_2,&__pyx_kp_3,&__pyx_kp_4,&__pyx_kp_5,&__pyx_kp_6,&__pyx_kp_7,&__pyx_kp_8,&__pyx_kp_alpha_c,0};
  __Pyx_SetupRefcountContext("__init__");
  if (unlikely(__pyx_kwds)) {
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    PyObject* values[9] = {0,0,0,0,0,0,0,0,0};
    values[8] = __pyx_int_0;
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  9: values[8] = PyTuple_GET_ITEM(__pyx_args, 8);
      case  8: values[7] = PyTuple_GET_ITEM(__pyx_args, 7);
      case  7: values[6] = PyTuple_GET_ITEM(__pyx_args, 6);
      case  6: values[5] = PyTuple_GET_ITEM(__pyx_args, 5);
      case  5: values[4] = PyTuple_GET_ITEM(__pyx_args, 4);
      case  4: values[3] = PyTuple_GET_ITEM(__pyx_args, 3);
      case  3: values[2] = PyTuple_GET_ITEM(__pyx_args, 2);
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_kp_1);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
      case  1:
      values[1] = PyDict_GetItem(__pyx_kwds, __pyx_kp_2);
      if (likely(values[1])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("__init__", 0, 8, 9, 1); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  2:
      values[2] = PyDict_GetItem(__pyx_kwds, __pyx_kp_3);
      if (likely(values[2])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("__init__", 0, 8, 9, 2); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  3:
      values[3] = PyDict_GetItem(__pyx_kwds, __pyx_kp_4);
      if (likely(values[3])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("__init__", 0, 8, 9, 3); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  4:
      values[4] = PyDict_GetItem(__pyx_kwds, __pyx_kp_5);
      if (likely(values[4])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("__init__", 0, 8, 9, 4); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  5:
      values[5] = PyDict_GetItem(__pyx_kwds, __pyx_kp_6);
      if (likely(values[5])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("__init__", 0, 8, 9, 5); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  6:
      values[6] = PyDict_GetItem(__pyx_kwds, __pyx_kp_7);
      if (likely(values[6])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("__init__", 0, 8, 9, 6); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  7:
      values[7] = PyDict_GetItem(__pyx_kwds, __pyx_kp_8);
      if (likely(values[7])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("__init__", 0, 8, 9, 7); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  8:
      if (kw_args > 1) {
        PyObject* value = PyDict_GetItem(__pyx_kwds, __pyx_kp_alpha_c);
        if (unlikely(value)) { values[8] = value; kw_args--; }
      }
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "__init__") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_fc1 = values[0];
    __pyx_v_fc2 = values[1];
    __pyx_v_cc1 = values[2];
    __pyx_v_cc2 = values[3];
    __pyx_v_k1 = values[4];
    __pyx_v_k2 = values[5];
    __pyx_v_p1 = values[6];
    __pyx_v_p2 = values[7];
    __pyx_v_alpha_c = values[8];
  } else {
    __pyx_v_alpha_c = __pyx_int_0;
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  9:
      __pyx_v_alpha_c = PyTuple_GET_ITEM(__pyx_args, 8);
      case  8:
      __pyx_v_p2 = PyTuple_GET_ITEM(__pyx_args, 7);
      __pyx_v_p1 = PyTuple_GET_ITEM(__pyx_args, 6);
      __pyx_v_k2 = PyTuple_GET_ITEM(__pyx_args, 5);
      __pyx_v_k1 = PyTuple_GET_ITEM(__pyx_args, 4);
      __pyx_v_cc2 = PyTuple_GET_ITEM(__pyx_args, 3);
      __pyx_v_cc1 = PyTuple_GET_ITEM(__pyx_args, 2);
      __pyx_v_fc2 = PyTuple_GET_ITEM(__pyx_args, 1);
      __pyx_v_fc1 = PyTuple_GET_ITEM(__pyx_args, 0);
      break;
      default: goto __pyx_L5_argtuple_error;
    }
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("__init__", 0, 8, 9, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("_caltech_distortion.CaltechDistortion.__init__");
  return -1;
  __pyx_L4_argument_unpacking_done:;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":21
 *         alpha_c - skew between X and Y pixel axes
 *         """
 *         self.fc1 = fc1             # <<<<<<<<<<<<<<
 *         self.fc2 = fc2
 *         self.cc1 = cc1
 */
  __pyx_t_1 = __pyx_PyFloat_AsDouble(__pyx_v_fc1); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->fc1 = __pyx_t_1;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":22
 *         """
 *         self.fc1 = fc1
 *         self.fc2 = fc2             # <<<<<<<<<<<<<<
 *         self.cc1 = cc1
 *         self.cc2 = cc2
 */
  __pyx_t_1 = __pyx_PyFloat_AsDouble(__pyx_v_fc2); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->fc2 = __pyx_t_1;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":23
 *         self.fc1 = fc1
 *         self.fc2 = fc2
 *         self.cc1 = cc1             # <<<<<<<<<<<<<<
 *         self.cc2 = cc2
 *         self.k1 = k1
 */
  __pyx_t_1 = __pyx_PyFloat_AsDouble(__pyx_v_cc1); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->cc1 = __pyx_t_1;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":24
 *         self.fc2 = fc2
 *         self.cc1 = cc1
 *         self.cc2 = cc2             # <<<<<<<<<<<<<<
 *         self.k1 = k1
 *         self.k2 = k2
 */
  __pyx_t_1 = __pyx_PyFloat_AsDouble(__pyx_v_cc2); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->cc2 = __pyx_t_1;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":25
 *         self.cc1 = cc1
 *         self.cc2 = cc2
 *         self.k1 = k1             # <<<<<<<<<<<<<<
 *         self.k2 = k2
 *         self.p1 = p1
 */
  __pyx_t_1 = __pyx_PyFloat_AsDouble(__pyx_v_k1); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->k1 = __pyx_t_1;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":26
 *         self.cc2 = cc2
 *         self.k1 = k1
 *         self.k2 = k2             # <<<<<<<<<<<<<<
 *         self.p1 = p1
 *         self.p2 = p2
 */
  __pyx_t_1 = __pyx_PyFloat_AsDouble(__pyx_v_k2); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->k2 = __pyx_t_1;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":27
 *         self.k1 = k1
 *         self.k2 = k2
 *         self.p1 = p1             # <<<<<<<<<<<<<<
 *         self.p2 = p2
 *         self.alpha_c = alpha_c
 */
  __pyx_t_1 = __pyx_PyFloat_AsDouble(__pyx_v_p1); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->p1 = __pyx_t_1;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":28
 *         self.k2 = k2
 *         self.p1 = p1
 *         self.p2 = p2             # <<<<<<<<<<<<<<
 *         self.alpha_c = alpha_c
 * 
 */
  __pyx_t_1 = __pyx_PyFloat_AsDouble(__pyx_v_p2); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->p2 = __pyx_t_1;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":29
 *         self.p1 = p1
 *         self.p2 = p2
 *         self.alpha_c = alpha_c             # <<<<<<<<<<<<<<
 * 
 *     def __reduce__(self):
 */
  __pyx_t_1 = __pyx_PyFloat_AsDouble(__pyx_v_alpha_c); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->alpha_c = __pyx_t_1;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_AddTraceback("_caltech_distortion.CaltechDistortion.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  __Pyx_FinishRefcountContext();
  return __pyx_r;
}

/* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":31
 *         self.alpha_c = alpha_c
 * 
 *     def __reduce__(self):             # <<<<<<<<<<<<<<
 *         """this allows CaltechDistortion to be pickled"""
 *         args = (self.fc1, self.fc2, self.cc1, self.cc2,
 */

static PyObject *__pyx_pf_19_caltech_distortion_17CaltechDistortion___reduce__(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static char __pyx_doc_19_caltech_distortion_17CaltechDistortion___reduce__[] = "this allows CaltechDistortion to be pickled";
static PyObject *__pyx_pf_19_caltech_distortion_17CaltechDistortion___reduce__(PyObject *__pyx_v_self, PyObject *unused) {
  PyObject *__pyx_v_args;
  PyObject *__pyx_r = NULL;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_t_1 = NULL;
  PyObject *__pyx_t_2 = NULL;
  PyObject *__pyx_t_3 = NULL;
  PyObject *__pyx_t_4 = NULL;
  PyObject *__pyx_t_5 = NULL;
  PyObject *__pyx_t_6 = NULL;
  PyObject *__pyx_t_7 = NULL;
  PyObject *__pyx_t_8 = NULL;
  PyObject *__pyx_t_9 = NULL;
  PyObject *__pyx_t_10 = NULL;
  __Pyx_SetupRefcountContext("__reduce__");
  __pyx_v_args = Py_None; __Pyx_INCREF(Py_None);

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":33
 *     def __reduce__(self):
 *         """this allows CaltechDistortion to be pickled"""
 *         args = (self.fc1, self.fc2, self.cc1, self.cc2,             # <<<<<<<<<<<<<<
 *                 self.k1, self.k2, self.p1, self.p2, self.alpha_c)
 *         return (make_CaltechDistortion, args)
 */
  __pyx_t_1 = PyFloat_FromDouble(((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->fc1); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_t_2 = PyFloat_FromDouble(((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->fc2); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  __pyx_t_3 = PyFloat_FromDouble(((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->cc1); if (unlikely(!__pyx_t_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_3);
  __pyx_t_4 = PyFloat_FromDouble(((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->cc2); if (unlikely(!__pyx_t_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_4);

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":34
 *         """this allows CaltechDistortion to be pickled"""
 *         args = (self.fc1, self.fc2, self.cc1, self.cc2,
 *                 self.k1, self.k2, self.p1, self.p2, self.alpha_c)             # <<<<<<<<<<<<<<
 *         return (make_CaltechDistortion, args)
 * 
 */
  __pyx_t_5 = PyFloat_FromDouble(((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->k1); if (unlikely(!__pyx_t_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_5);
  __pyx_t_6 = PyFloat_FromDouble(((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->k2); if (unlikely(!__pyx_t_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_6);
  __pyx_t_7 = PyFloat_FromDouble(((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->p1); if (unlikely(!__pyx_t_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_7);
  __pyx_t_8 = PyFloat_FromDouble(((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->p2); if (unlikely(!__pyx_t_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_8);
  __pyx_t_9 = PyFloat_FromDouble(((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->alpha_c); if (unlikely(!__pyx_t_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_9);
  __pyx_t_10 = PyTuple_New(9); if (unlikely(!__pyx_t_10)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(((PyObject *)__pyx_t_10));
  PyTuple_SET_ITEM(__pyx_t_10, 0, __pyx_t_1);
  __Pyx_GIVEREF(__pyx_t_1);
  PyTuple_SET_ITEM(__pyx_t_10, 1, __pyx_t_2);
  __Pyx_GIVEREF(__pyx_t_2);
  PyTuple_SET_ITEM(__pyx_t_10, 2, __pyx_t_3);
  __Pyx_GIVEREF(__pyx_t_3);
  PyTuple_SET_ITEM(__pyx_t_10, 3, __pyx_t_4);
  __Pyx_GIVEREF(__pyx_t_4);
  PyTuple_SET_ITEM(__pyx_t_10, 4, __pyx_t_5);
  __Pyx_GIVEREF(__pyx_t_5);
  PyTuple_SET_ITEM(__pyx_t_10, 5, __pyx_t_6);
  __Pyx_GIVEREF(__pyx_t_6);
  PyTuple_SET_ITEM(__pyx_t_10, 6, __pyx_t_7);
  __Pyx_GIVEREF(__pyx_t_7);
  PyTuple_SET_ITEM(__pyx_t_10, 7, __pyx_t_8);
  __Pyx_GIVEREF(__pyx_t_8);
  PyTuple_SET_ITEM(__pyx_t_10, 8, __pyx_t_9);
  __Pyx_GIVEREF(__pyx_t_9);
  __pyx_t_1 = 0;
  __pyx_t_2 = 0;
  __pyx_t_3 = 0;
  __pyx_t_4 = 0;
  __pyx_t_5 = 0;
  __pyx_t_6 = 0;
  __pyx_t_7 = 0;
  __pyx_t_8 = 0;
  __pyx_t_9 = 0;
  __Pyx_DECREF(__pyx_v_args);
  __pyx_v_args = ((PyObject *)__pyx_t_10);
  __pyx_t_10 = 0;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":35
 *         args = (self.fc1, self.fc2, self.cc1, self.cc2,
 *                 self.k1, self.k2, self.p1, self.p2, self.alpha_c)
 *         return (make_CaltechDistortion, args)             # <<<<<<<<<<<<<<
 * 
 *     def undistort(self, double x_kk, double y_kk):
 */
  __Pyx_XDECREF(__pyx_r);
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_kp_9); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_1);
  __pyx_t_10 = PyTuple_New(2); if (unlikely(!__pyx_t_10)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(((PyObject *)__pyx_t_10));
  PyTuple_SET_ITEM(__pyx_t_10, 0, __pyx_1);
  __Pyx_GIVEREF(__pyx_1);
  __Pyx_INCREF(__pyx_v_args);
  PyTuple_SET_ITEM(__pyx_t_10, 1, __pyx_v_args);
  __Pyx_GIVEREF(__pyx_v_args);
  __pyx_1 = 0;
  __pyx_r = ((PyObject *)__pyx_t_10);
  __pyx_t_10 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_1);
  __Pyx_XDECREF(__pyx_t_1);
  __Pyx_XDECREF(__pyx_t_2);
  __Pyx_XDECREF(__pyx_t_3);
  __Pyx_XDECREF(__pyx_t_4);
  __Pyx_XDECREF(__pyx_t_5);
  __Pyx_XDECREF(__pyx_t_6);
  __Pyx_XDECREF(__pyx_t_7);
  __Pyx_XDECREF(__pyx_t_8);
  __Pyx_XDECREF(__pyx_t_9);
  __Pyx_XDECREF(__pyx_t_10);
  __Pyx_AddTraceback("_caltech_distortion.CaltechDistortion.__reduce__");
  __pyx_r = NULL;
  __pyx_L0:;
  __Pyx_DECREF(__pyx_v_args);
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_FinishRefcountContext();
  return __pyx_r;
}

/* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":37
 *         return (make_CaltechDistortion, args)
 * 
 *     def undistort(self, double x_kk, double y_kk):             # <<<<<<<<<<<<<<
 *         """undistort 2D coordinate pair
 * 
 */

static PyObject *__pyx_pf_19_caltech_distortion_17CaltechDistortion_undistort(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_19_caltech_distortion_17CaltechDistortion_undistort[] = "undistort 2D coordinate pair\n\n        Iteratively performs an undistortion using camera intrinsic\n        parameters.\n\n        Implementation translated from CalTechCal.\n\n        See also the OpenCV reference manual, which has the equation\n        used.\n        ";
static PyObject *__pyx_pf_19_caltech_distortion_17CaltechDistortion_undistort(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  double __pyx_v_x_kk;
  double __pyx_v_y_kk;
  double __pyx_v_xl;
  double __pyx_v_yl;
  double __pyx_v_xd;
  double __pyx_v_yd;
  double __pyx_v_x;
  double __pyx_v_y;
  double __pyx_v_r_2;
  double __pyx_v_k_radial;
  double __pyx_v_delta_x;
  double __pyx_v_delta_y;
  int __pyx_v_i;
  PyObject *__pyx_r = NULL;
  PyObject *__pyx_t_1 = NULL;
  PyObject *__pyx_t_2 = NULL;
  PyObject *__pyx_t_3 = NULL;
  static PyObject **__pyx_pyargnames[] = {&__pyx_kp_x_kk,&__pyx_kp_y_kk,0};
  __Pyx_SetupRefcountContext("undistort");
  if (unlikely(__pyx_kwds)) {
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    PyObject* values[2] = {0,0};
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_kp_x_kk);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
      case  1:
      values[1] = PyDict_GetItem(__pyx_kwds, __pyx_kp_y_kk);
      if (likely(values[1])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("undistort", 1, 2, 2, 1); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "undistort") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_x_kk = __pyx_PyFloat_AsDouble(values[0]); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    __pyx_v_y_kk = __pyx_PyFloat_AsDouble(values[1]); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  } else if (PyTuple_GET_SIZE(__pyx_args) != 2) {
    goto __pyx_L5_argtuple_error;
  } else {
    __pyx_v_x_kk = __pyx_PyFloat_AsDouble(PyTuple_GET_ITEM(__pyx_args, 0)); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    __pyx_v_y_kk = __pyx_PyFloat_AsDouble(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("undistort", 1, 2, 2, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("_caltech_distortion.CaltechDistortion.undistort");
  return NULL;
  __pyx_L4_argument_unpacking_done:;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":57
 *         # undoradial.m / CalTechCal/normalize.m
 * 
 *         xd = ( x_kk - self.cc1 ) / self.fc1             # <<<<<<<<<<<<<<
 *         yd = ( y_kk - self.cc2 ) / self.fc2
 * 
 */
  __pyx_v_xd = ((__pyx_v_x_kk - ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->cc1) / ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->fc1);

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":58
 * 
 *         xd = ( x_kk - self.cc1 ) / self.fc1
 *         yd = ( y_kk - self.cc2 ) / self.fc2             # <<<<<<<<<<<<<<
 * 
 *         xd = xd - self.alpha_c * yd
 */
  __pyx_v_yd = ((__pyx_v_y_kk - ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->cc2) / ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->fc2);

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":60
 *         yd = ( y_kk - self.cc2 ) / self.fc2
 * 
 *         xd = xd - self.alpha_c * yd             # <<<<<<<<<<<<<<
 * 
 *         # comp_distortion_oulu.m
 */
  __pyx_v_xd = (__pyx_v_xd - (((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->alpha_c * __pyx_v_yd));

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":65
 * 
 *         # initial guess
 *         x = xd             # <<<<<<<<<<<<<<
 *         y = yd
 * 
 */
  __pyx_v_x = __pyx_v_xd;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":66
 *         # initial guess
 *         x = xd
 *         y = yd             # <<<<<<<<<<<<<<
 * 
 *         for i from 0<=i<20:
 */
  __pyx_v_y = __pyx_v_yd;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":68
 *         y = yd
 * 
 *         for i from 0<=i<20:             # <<<<<<<<<<<<<<
 *             r_2 = x*x + y*y
 *             k_radial = 1.0 + (self.k1) * r_2 + (self.k2) * r_2*r_2
 */
  for (__pyx_v_i = 0; __pyx_v_i < 20; __pyx_v_i++) {

    /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":69
 * 
 *         for i from 0<=i<20:
 *             r_2 = x*x + y*y             # <<<<<<<<<<<<<<
 *             k_radial = 1.0 + (self.k1) * r_2 + (self.k2) * r_2*r_2
 *             delta_x = 2.0 * (self.p1)*x*y + (self.p2)*(r_2 + 2.0*x*x)
 */
    __pyx_v_r_2 = ((__pyx_v_x * __pyx_v_x) + (__pyx_v_y * __pyx_v_y));

    /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":70
 *         for i from 0<=i<20:
 *             r_2 = x*x + y*y
 *             k_radial = 1.0 + (self.k1) * r_2 + (self.k2) * r_2*r_2             # <<<<<<<<<<<<<<
 *             delta_x = 2.0 * (self.p1)*x*y + (self.p2)*(r_2 + 2.0*x*x)
 *             delta_y = (self.p1) * (r_2 + 2.0*y*y)+2.0*(self.p2)*x*y
 */
    __pyx_v_k_radial = ((1.0 + (((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->k1 * __pyx_v_r_2)) + ((((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->k2 * __pyx_v_r_2) * __pyx_v_r_2));

    /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":71
 *             r_2 = x*x + y*y
 *             k_radial = 1.0 + (self.k1) * r_2 + (self.k2) * r_2*r_2
 *             delta_x = 2.0 * (self.p1)*x*y + (self.p2)*(r_2 + 2.0*x*x)             # <<<<<<<<<<<<<<
 *             delta_y = (self.p1) * (r_2 + 2.0*y*y)+2.0*(self.p2)*x*y
 *             x = (xd-delta_x)/k_radial
 */
    __pyx_v_delta_x = ((((2.0 * ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->p1) * __pyx_v_x) * __pyx_v_y) + (((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->p2 * (__pyx_v_r_2 + ((2.0 * __pyx_v_x) * __pyx_v_x))));

    /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":72
 *             k_radial = 1.0 + (self.k1) * r_2 + (self.k2) * r_2*r_2
 *             delta_x = 2.0 * (self.p1)*x*y + (self.p2)*(r_2 + 2.0*x*x)
 *             delta_y = (self.p1) * (r_2 + 2.0*y*y)+2.0*(self.p2)*x*y             # <<<<<<<<<<<<<<
 *             x = (xd-delta_x)/k_radial
 *             y = (yd-delta_y)/k_radial
 */
    __pyx_v_delta_y = ((((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->p1 * (__pyx_v_r_2 + ((2.0 * __pyx_v_y) * __pyx_v_y))) + (((2.0 * ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->p2) * __pyx_v_x) * __pyx_v_y));

    /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":73
 *             delta_x = 2.0 * (self.p1)*x*y + (self.p2)*(r_2 + 2.0*x*x)
 *             delta_y = (self.p1) * (r_2 + 2.0*y*y)+2.0*(self.p2)*x*y
 *             x = (xd-delta_x)/k_radial             # <<<<<<<<<<<<<<
 *             y = (yd-delta_y)/k_radial
 * 
 */
    __pyx_v_x = ((__pyx_v_xd - __pyx_v_delta_x) / __pyx_v_k_radial);

    /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":74
 *             delta_y = (self.p1) * (r_2 + 2.0*y*y)+2.0*(self.p2)*x*y
 *             x = (xd-delta_x)/k_radial
 *             y = (yd-delta_y)/k_radial             # <<<<<<<<<<<<<<
 * 
 *         # undoradial.m
 */
    __pyx_v_y = ((__pyx_v_yd - __pyx_v_delta_y) / __pyx_v_k_radial);
  }

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":78
 *         # undoradial.m
 * 
 *         xl = (self.fc1)*x + (self.fc1*self.alpha_c)*y + (self.cc1)             # <<<<<<<<<<<<<<
 *         yl = (self.fc2)*y + (self.cc2)
 *         return (xl, yl)
 */
  __pyx_v_xl = (((((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->fc1 * __pyx_v_x) + ((((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->fc1 * ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->alpha_c) * __pyx_v_y)) + ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->cc1);

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":79
 * 
 *         xl = (self.fc1)*x + (self.fc1*self.alpha_c)*y + (self.cc1)
 *         yl = (self.fc2)*y + (self.cc2)             # <<<<<<<<<<<<<<
 *         return (xl, yl)
 * 
 */
  __pyx_v_yl = ((((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->fc2 * __pyx_v_y) + ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->cc2);

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":80
 *         xl = (self.fc1)*x + (self.fc1*self.alpha_c)*y + (self.cc1)
 *         yl = (self.fc2)*y + (self.cc2)
 *         return (xl, yl)             # <<<<<<<<<<<<<<
 * 
 *     def distort(self, double xl, double yl):
 */
  __Pyx_XDECREF(__pyx_r);
  __pyx_t_1 = PyFloat_FromDouble(__pyx_v_xl); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_t_2 = PyFloat_FromDouble(__pyx_v_yl); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  __pyx_t_3 = PyTuple_New(2); if (unlikely(!__pyx_t_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(((PyObject *)__pyx_t_3));
  PyTuple_SET_ITEM(__pyx_t_3, 0, __pyx_t_1);
  __Pyx_GIVEREF(__pyx_t_1);
  PyTuple_SET_ITEM(__pyx_t_3, 1, __pyx_t_2);
  __Pyx_GIVEREF(__pyx_t_2);
  __pyx_t_1 = 0;
  __pyx_t_2 = 0;
  __pyx_r = ((PyObject *)__pyx_t_3);
  __pyx_t_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_1);
  __Pyx_XDECREF(__pyx_t_2);
  __Pyx_XDECREF(__pyx_t_3);
  __Pyx_AddTraceback("_caltech_distortion.CaltechDistortion.undistort");
  __pyx_r = NULL;
  __pyx_L0:;
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_FinishRefcountContext();
  return __pyx_r;
}

/* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":82
 *         return (xl, yl)
 * 
 *     def distort(self, double xl, double yl):             # <<<<<<<<<<<<<<
 *         """distort 2D coordinate pair"""
 * 
 */

static PyObject *__pyx_pf_19_caltech_distortion_17CaltechDistortion_distort(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_19_caltech_distortion_17CaltechDistortion_distort[] = "distort 2D coordinate pair";
static PyObject *__pyx_pf_19_caltech_distortion_17CaltechDistortion_distort(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  double __pyx_v_xl;
  double __pyx_v_yl;
  double __pyx_v_x;
  double __pyx_v_y;
  double __pyx_v_r_2;
  double __pyx_v_term1;
  double __pyx_v_xd;
  double __pyx_v_yd;
  PyObject *__pyx_v_r_4;
  PyObject *__pyx_r = NULL;
  PyObject *__pyx_t_1 = NULL;
  PyObject *__pyx_t_2 = NULL;
  PyObject *__pyx_t_3 = NULL;
  double __pyx_t_4;
  static PyObject **__pyx_pyargnames[] = {&__pyx_kp_xl,&__pyx_kp_yl,0};
  __Pyx_SetupRefcountContext("distort");
  if (unlikely(__pyx_kwds)) {
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    PyObject* values[2] = {0,0};
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_kp_xl);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
      case  1:
      values[1] = PyDict_GetItem(__pyx_kwds, __pyx_kp_yl);
      if (likely(values[1])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("distort", 1, 2, 2, 1); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "distort") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_xl = __pyx_PyFloat_AsDouble(values[0]); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    __pyx_v_yl = __pyx_PyFloat_AsDouble(values[1]); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  } else if (PyTuple_GET_SIZE(__pyx_args) != 2) {
    goto __pyx_L5_argtuple_error;
  } else {
    __pyx_v_xl = __pyx_PyFloat_AsDouble(PyTuple_GET_ITEM(__pyx_args, 0)); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    __pyx_v_yl = __pyx_PyFloat_AsDouble(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("distort", 1, 2, 2, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("_caltech_distortion.CaltechDistortion.distort");
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  __pyx_v_r_4 = Py_None; __Pyx_INCREF(Py_None);

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":87
 *         cdef double x, y, r_2, term1, xd, yd
 * 
 *         x = ( xl - self.cc1 ) / self.fc1             # <<<<<<<<<<<<<<
 *         y = ( yl - self.cc2 ) / self.fc2
 * 
 */
  __pyx_v_x = ((__pyx_v_xl - ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->cc1) / ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->fc1);

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":88
 * 
 *         x = ( xl - self.cc1 ) / self.fc1
 *         y = ( yl - self.cc2 ) / self.fc2             # <<<<<<<<<<<<<<
 * 
 *         r_2 = x*x + y*y
 */
  __pyx_v_y = ((__pyx_v_yl - ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->cc2) / ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->fc2);

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":90
 *         y = ( yl - self.cc2 ) / self.fc2
 * 
 *         r_2 = x*x + y*y             # <<<<<<<<<<<<<<
 *         r_4 = r_2**2
 *         term1 = self.k1*r_2 + self.k2*r_4
 */
  __pyx_v_r_2 = ((__pyx_v_x * __pyx_v_x) + (__pyx_v_y * __pyx_v_y));

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":91
 * 
 *         r_2 = x*x + y*y
 *         r_4 = r_2**2             # <<<<<<<<<<<<<<
 *         term1 = self.k1*r_2 + self.k2*r_4
 * 
 */
  __pyx_t_1 = PyFloat_FromDouble(pow(__pyx_v_r_2, 2)); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_1);
  __Pyx_DECREF(__pyx_v_r_4);
  __pyx_v_r_4 = __pyx_t_1;
  __pyx_t_1 = 0;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":92
 *         r_2 = x*x + y*y
 *         r_4 = r_2**2
 *         term1 = self.k1*r_2 + self.k2*r_4             # <<<<<<<<<<<<<<
 * 
 *         # OpenCV manual (chaper 6, "3D reconstruction", "camera
 */
  __pyx_t_1 = PyFloat_FromDouble((((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->k1 * __pyx_v_r_2)); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_t_2 = PyFloat_FromDouble(((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->k2); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  __pyx_t_3 = PyNumber_Multiply(__pyx_t_2, __pyx_v_r_4); if (unlikely(!__pyx_t_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_3);
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;
  __pyx_t_2 = PyNumber_Add(__pyx_t_1, __pyx_t_3); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
  __Pyx_DECREF(__pyx_t_3); __pyx_t_3 = 0;
  __pyx_t_4 = __pyx_PyFloat_AsDouble(__pyx_t_2); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;
  __pyx_v_term1 = __pyx_t_4;

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":102
 *         # consistent with his webpage and this below.
 * 
 *         xd = x + x*term1 + (2*self.p1*x*y + self.p2*(r_2+2*x**2))             # <<<<<<<<<<<<<<
 *         yd = y + y*term1 + (self.p1*(r_2+2*y**2) + 2*self.p2*x*y)
 * 
 */
  __pyx_v_xd = ((__pyx_v_x + (__pyx_v_x * __pyx_v_term1)) + ((((2 * ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->p1) * __pyx_v_x) * __pyx_v_y) + (((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->p2 * (__pyx_v_r_2 + (2 * pow(__pyx_v_x, 2))))));

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":103
 * 
 *         xd = x + x*term1 + (2*self.p1*x*y + self.p2*(r_2+2*x**2))
 *         yd = y + y*term1 + (self.p1*(r_2+2*y**2) + 2*self.p2*x*y)             # <<<<<<<<<<<<<<
 * 
 *         xd = (self.fc1)*xd + (self.cc1)
 */
  __pyx_v_yd = ((__pyx_v_y + (__pyx_v_y * __pyx_v_term1)) + ((((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->p1 * (__pyx_v_r_2 + (2 * pow(__pyx_v_y, 2)))) + (((2 * ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->p2) * __pyx_v_x) * __pyx_v_y)));

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":105
 *         yd = y + y*term1 + (self.p1*(r_2+2*y**2) + 2*self.p2*x*y)
 * 
 *         xd = (self.fc1)*xd + (self.cc1)             # <<<<<<<<<<<<<<
 *         yd = (self.fc2)*yd + (self.cc2)
 * 
 */
  __pyx_v_xd = ((((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->fc1 * __pyx_v_xd) + ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->cc1);

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":106
 * 
 *         xd = (self.fc1)*xd + (self.cc1)
 *         yd = (self.fc2)*yd + (self.cc2)             # <<<<<<<<<<<<<<
 * 
 *         return (xd, yd)
 */
  __pyx_v_yd = ((((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->fc2 * __pyx_v_yd) + ((struct __pyx_obj_19_caltech_distortion_CaltechDistortion *)__pyx_v_self)->cc2);

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":108
 *         yd = (self.fc2)*yd + (self.cc2)
 * 
 *         return (xd, yd)             # <<<<<<<<<<<<<<
 */
  __Pyx_XDECREF(__pyx_r);
  __pyx_t_2 = PyFloat_FromDouble(__pyx_v_xd); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  __pyx_t_3 = PyFloat_FromDouble(__pyx_v_yd); if (unlikely(!__pyx_t_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_3);
  __pyx_t_1 = PyTuple_New(2); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(((PyObject *)__pyx_t_1));
  PyTuple_SET_ITEM(__pyx_t_1, 0, __pyx_t_2);
  __Pyx_GIVEREF(__pyx_t_2);
  PyTuple_SET_ITEM(__pyx_t_1, 1, __pyx_t_3);
  __Pyx_GIVEREF(__pyx_t_3);
  __pyx_t_2 = 0;
  __pyx_t_3 = 0;
  __pyx_r = ((PyObject *)__pyx_t_1);
  __pyx_t_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_1);
  __Pyx_XDECREF(__pyx_t_2);
  __Pyx_XDECREF(__pyx_t_3);
  __Pyx_AddTraceback("_caltech_distortion.CaltechDistortion.distort");
  __pyx_r = NULL;
  __pyx_L0:;
  __Pyx_DECREF(__pyx_v_r_4);
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_FinishRefcountContext();
  return __pyx_r;
}

static PyObject *__pyx_tp_new_19_caltech_distortion_CaltechDistortion(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_19_caltech_distortion_CaltechDistortion(PyObject *o) {
  (*Py_TYPE(o)->tp_free)(o);
}

static struct PyMethodDef __pyx_methods_19_caltech_distortion_CaltechDistortion[] = {
  {__Pyx_NAMESTR("__reduce__"), (PyCFunction)__pyx_pf_19_caltech_distortion_17CaltechDistortion___reduce__, METH_NOARGS, __Pyx_DOCSTR(__pyx_doc_19_caltech_distortion_17CaltechDistortion___reduce__)},
  {__Pyx_NAMESTR("undistort"), (PyCFunction)__pyx_pf_19_caltech_distortion_17CaltechDistortion_undistort, METH_VARARGS|METH_KEYWORDS, __Pyx_DOCSTR(__pyx_doc_19_caltech_distortion_17CaltechDistortion_undistort)},
  {__Pyx_NAMESTR("distort"), (PyCFunction)__pyx_pf_19_caltech_distortion_17CaltechDistortion_distort, METH_VARARGS|METH_KEYWORDS, __Pyx_DOCSTR(__pyx_doc_19_caltech_distortion_17CaltechDistortion_distort)},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_19_caltech_distortion_CaltechDistortion[] = {
  {(char *)"fc1", T_DOUBLE, offsetof(struct __pyx_obj_19_caltech_distortion_CaltechDistortion, fc1), READONLY, 0},
  {(char *)"fc2", T_DOUBLE, offsetof(struct __pyx_obj_19_caltech_distortion_CaltechDistortion, fc2), READONLY, 0},
  {(char *)"cc1", T_DOUBLE, offsetof(struct __pyx_obj_19_caltech_distortion_CaltechDistortion, cc1), READONLY, 0},
  {(char *)"cc2", T_DOUBLE, offsetof(struct __pyx_obj_19_caltech_distortion_CaltechDistortion, cc2), READONLY, 0},
  {(char *)"k1", T_DOUBLE, offsetof(struct __pyx_obj_19_caltech_distortion_CaltechDistortion, k1), READONLY, 0},
  {(char *)"k2", T_DOUBLE, offsetof(struct __pyx_obj_19_caltech_distortion_CaltechDistortion, k2), READONLY, 0},
  {(char *)"p1", T_DOUBLE, offsetof(struct __pyx_obj_19_caltech_distortion_CaltechDistortion, p1), READONLY, 0},
  {(char *)"p2", T_DOUBLE, offsetof(struct __pyx_obj_19_caltech_distortion_CaltechDistortion, p2), READONLY, 0},
  {(char *)"alpha_c", T_DOUBLE, offsetof(struct __pyx_obj_19_caltech_distortion_CaltechDistortion, alpha_c), READONLY, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_CaltechDistortion = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_divide*/
  #endif
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_coerce*/
  #endif
  0, /*nb_int*/
  #if PY_MAJOR_VERSION >= 3
  0, /*reserved*/
  #else
  0, /*nb_long*/
  #endif
  0, /*nb_float*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_oct*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*nb_hex*/
  #endif
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_inplace_divide*/
  #endif
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if (PY_MAJOR_VERSION >= 3) || (Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX)
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_CaltechDistortion = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_CaltechDistortion = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_CaltechDistortion = {
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getreadbuffer*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getwritebuffer*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getsegcount*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getcharbuffer*/
  #endif
  #if PY_VERSION_HEX >= 0x02060000
  0, /*bf_getbuffer*/
  #endif
  #if PY_VERSION_HEX >= 0x02060000
  0, /*bf_releasebuffer*/
  #endif
};

PyTypeObject __pyx_type_19_caltech_distortion_CaltechDistortion = {
  PyVarObject_HEAD_INIT(0, 0)
  __Pyx_NAMESTR("_caltech_distortion.CaltechDistortion"), /*tp_name*/
  sizeof(struct __pyx_obj_19_caltech_distortion_CaltechDistortion), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_19_caltech_distortion_CaltechDistortion, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_CaltechDistortion, /*tp_as_number*/
  &__pyx_tp_as_sequence_CaltechDistortion, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_CaltechDistortion, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_CaltechDistortion, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_NEWBUFFER, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_19_caltech_distortion_CaltechDistortion, /*tp_methods*/
  __pyx_members_19_caltech_distortion_CaltechDistortion, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_pf_19_caltech_distortion_17CaltechDistortion___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_19_caltech_distortion_CaltechDistortion, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {__Pyx_NAMESTR("make_CaltechDistortion"), (PyCFunction)__pyx_pf_19_caltech_distortion_make_CaltechDistortion, METH_VARARGS|METH_KEYWORDS, __Pyx_DOCSTR(0)},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    __Pyx_NAMESTR("_caltech_distortion"),
    0, /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp___main__, __pyx_k___main__, sizeof(__pyx_k___main__), 1, 1, 1},
  {&__pyx_kp___init__, __pyx_k___init__, sizeof(__pyx_k___init__), 1, 1, 1},
  {&__pyx_kp___reduce__, __pyx_k___reduce__, sizeof(__pyx_k___reduce__), 1, 1, 1},
  {&__pyx_kp_undistort, __pyx_k_undistort, sizeof(__pyx_k_undistort), 1, 1, 1},
  {&__pyx_kp_distort, __pyx_k_distort, sizeof(__pyx_k_distort), 1, 1, 1},
  {&__pyx_kp_1, __pyx_k_1, sizeof(__pyx_k_1), 1, 1, 1},
  {&__pyx_kp_2, __pyx_k_2, sizeof(__pyx_k_2), 1, 1, 1},
  {&__pyx_kp_3, __pyx_k_3, sizeof(__pyx_k_3), 1, 1, 1},
  {&__pyx_kp_4, __pyx_k_4, sizeof(__pyx_k_4), 1, 1, 1},
  {&__pyx_kp_5, __pyx_k_5, sizeof(__pyx_k_5), 1, 1, 1},
  {&__pyx_kp_6, __pyx_k_6, sizeof(__pyx_k_6), 1, 1, 1},
  {&__pyx_kp_7, __pyx_k_7, sizeof(__pyx_k_7), 1, 1, 1},
  {&__pyx_kp_8, __pyx_k_8, sizeof(__pyx_k_8), 1, 1, 1},
  {&__pyx_kp_alpha_c, __pyx_k_alpha_c, sizeof(__pyx_k_alpha_c), 1, 1, 1},
  {&__pyx_kp_x_kk, __pyx_k_x_kk, sizeof(__pyx_k_x_kk), 1, 1, 1},
  {&__pyx_kp_y_kk, __pyx_k_y_kk, sizeof(__pyx_k_y_kk), 1, 1, 1},
  {&__pyx_kp_xl, __pyx_k_xl, sizeof(__pyx_k_xl), 1, 1, 1},
  {&__pyx_kp_yl, __pyx_k_yl, sizeof(__pyx_k_yl), 1, 1, 1},
  {&__pyx_kp_9, __pyx_k_9, sizeof(__pyx_k_9), 1, 1, 1},
  {0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  return 0;
  return -1;
}

static int __Pyx_InitGlobals(void) {
  __pyx_int_0 = PyInt_FromLong(0); if (unlikely(!__pyx_int_0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_caltech_distortion(void); /*proto*/
PyMODINIT_FUNC init_caltech_distortion(void)
#else
PyMODINIT_FUNC PyInit__caltech_distortion(void); /*proto*/
PyMODINIT_FUNC PyInit__caltech_distortion(void)
#endif
{
  #ifdef CYTHON_REFNANNY
  void* __pyx_refchk = NULL;
  __Pyx_Refnanny = __Pyx_ImportRefcountAPI("refnanny");
  if (!__Pyx_Refnanny) {
      PyErr_Clear();
      __Pyx_Refnanny = __Pyx_ImportRefcountAPI("Cython.Runtime.refnanny");
      if (!__Pyx_Refnanny)
          Py_FatalError("failed to import refnanny module");
  }
  __pyx_refchk = __Pyx_Refnanny->NewContext("PyMODINIT_FUNC PyInit__caltech_distortion(void)", __LINE__, __FILE__);
  #endif
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Library function declarations ---*/
  __pyx_init_filenames();
  /*--- Threads initialization code ---*/
  #if defined(__PYX_FORCE_INIT_THREADS) && __PYX_FORCE_INIT_THREADS
  #ifdef WITH_THREAD /* Python build with threading support? */
  PyEval_InitThreads();
  #endif
  #endif
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4(__Pyx_NAMESTR("_caltech_distortion"), __pyx_methods, 0, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_NAMESTR(__Pyx_BUILTIN_MODULE_NAME));
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__Pyx_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__pyx_module_is_main__caltech_distortion) {
    if (__Pyx_SetAttrString(__pyx_m, "__name__", __pyx_kp___main__) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  }
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  if (PyType_Ready(&__pyx_type_19_caltech_distortion_CaltechDistortion) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_SetAttrString(__pyx_m, "CaltechDistortion", (PyObject *)&__pyx_type_19_caltech_distortion_CaltechDistortion) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_19_caltech_distortion_CaltechDistortion = &__pyx_type_19_caltech_distortion_CaltechDistortion;
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "/home/astraw/astraw-git-root/flydra/pinpoint/src/_caltech_distortion.pyx":82
 *         return (xl, yl)
 * 
 *     def distort(self, double xl, double yl):             # <<<<<<<<<<<<<<
 *         """distort 2D coordinate pair"""
 * 
 */
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_AddTraceback("_caltech_distortion");
  Py_DECREF(__pyx_m); __pyx_m = 0;
  __pyx_L0:;
  __Pyx_FinishRefcountContext();
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
}

static const char *__pyx_filenames[] = {
  "_caltech_distortion.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static INLINE int __Pyx_CheckKeywordStrings(
    PyObject *kwdict,
    const char* function_name,
    int kw_allowed)
{
    PyObject* key = 0;
    Py_ssize_t pos = 0;
    while (PyDict_Next(kwdict, &pos, &key, 0)) {
        #if PY_MAJOR_VERSION < 3
        if (unlikely(!PyString_CheckExact(key)) && unlikely(!PyString_Check(key)))
        #else
        if (unlikely(!PyUnicode_CheckExact(key)) && unlikely(!PyUnicode_Check(key)))
        #endif
            goto invalid_keyword_type;
    }
    if ((!kw_allowed) && unlikely(key))
        goto invalid_keyword;
    return 1;
invalid_keyword_type:
    PyErr_Format(PyExc_TypeError,
        "%s() keywords must be strings", function_name);
    return 0;
invalid_keyword:
    PyErr_Format(PyExc_TypeError,
    #if PY_MAJOR_VERSION < 3
        "%s() got an unexpected keyword argument '%s'",
        function_name, PyString_AsString(key));
    #else
        "%s() got an unexpected keyword argument '%U'",
        function_name, key);
    #endif
    return 0;
}

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name,
    PyObject* kw_name)
{
    PyErr_Format(PyExc_TypeError,
        #if PY_MAJOR_VERSION >= 3
        "%s() got multiple values for keyword argument '%U'", func_name, kw_name);
        #else
        "%s() got multiple values for keyword argument '%s'", func_name,
        PyString_AS_STRING(kw_name));
        #endif
}

static void __Pyx_RaiseArgtupleInvalid(
    const char* func_name,
    int exact,
    Py_ssize_t num_min,
    Py_ssize_t num_max,
    Py_ssize_t num_found)
{
    Py_ssize_t num_expected;
    const char *number, *more_or_less;

    if (num_found < num_min) {
        num_expected = num_min;
        more_or_less = "at least";
    } else {
        num_expected = num_max;
        more_or_less = "at most";
    }
    if (exact) {
        more_or_less = "exactly";
    }
    number = (num_expected == 1) ? "" : "s";
    PyErr_Format(PyExc_TypeError,
        #if PY_VERSION_HEX < 0x02050000
            "%s() takes %s %d positional argument%s (%d given)",
        #else
            "%s() takes %s %zd positional argument%s (%zd given)",
        #endif
        func_name, more_or_less, num_expected, number, num_found);
}

static int __Pyx_ParseOptionalKeywords(
    PyObject *kwds,
    PyObject **argnames[],
    PyObject *kwds2,
    PyObject *values[],
    Py_ssize_t num_pos_args,
    const char* function_name)
{
    PyObject *key = 0, *value = 0;
    Py_ssize_t pos = 0;
    PyObject*** name;
    PyObject*** first_kw_arg = argnames + num_pos_args;

    while (PyDict_Next(kwds, &pos, &key, &value)) {
        name = first_kw_arg;
        while (*name && (**name != key)) name++;
        if (*name) {
            values[name-argnames] = value;
        } else {
            #if PY_MAJOR_VERSION < 3
            if (unlikely(!PyString_CheckExact(key)) && unlikely(!PyString_Check(key))) {
            #else
            if (unlikely(!PyUnicode_CheckExact(key)) && unlikely(!PyUnicode_Check(key))) {
            #endif
                goto invalid_keyword_type;
            } else {
                for (name = first_kw_arg; *name; name++) {
                    #if PY_MAJOR_VERSION >= 3
                    if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                        PyUnicode_Compare(**name, key) == 0) break;
                    #else
                    if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                        _PyString_Eq(**name, key)) break;
                    #endif
                }
                if (*name) {
                    values[name-argnames] = value;
                } else {
                    /* unexpected keyword found */
                    for (name=argnames; name != first_kw_arg; name++) {
                        if (**name == key) goto arg_passed_twice;
                        #if PY_MAJOR_VERSION >= 3
                        if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                            PyUnicode_Compare(**name, key) == 0) goto arg_passed_twice;
                        #else
                        if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                            _PyString_Eq(**name, key)) goto arg_passed_twice;
                        #endif
                    }
                    if (kwds2) {
                        if (unlikely(PyDict_SetItem(kwds2, key, value))) goto bad;
                    } else {
                        goto invalid_keyword;
                    }
                }
            }
        }
    }
    return 0;
arg_passed_twice:
    __Pyx_RaiseDoubleKeywordsError(function_name, **name);
    goto bad;
invalid_keyword_type:
    PyErr_Format(PyExc_TypeError,
        "%s() keywords must be strings", function_name);
    goto bad;
invalid_keyword:
    PyErr_Format(PyExc_TypeError,
    #if PY_MAJOR_VERSION < 3
        "%s() got an unexpected keyword argument '%s'",
        function_name, PyString_AsString(key));
    #else
        "%s() got an unexpected keyword argument '%U'",
        function_name, key);
    #endif
bad:
    return -1;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static INLINE int __Pyx_StrEq(const char *s1, const char *s2) {
     while (*s1 != '\0' && *s1 == *s2) { s1++; s2++; }
     return *s1 == *s2;
}

static INLINE unsigned char __Pyx_PyInt_AsUnsignedChar(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned char)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (unsigned char)-1;
            if (unlikely(val < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned char");
                return (unsigned char)-1;
            }
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return (unsigned char)val;
    }
    return (unsigned char)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE unsigned short __Pyx_PyInt_AsUnsignedShort(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned short)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (unsigned short)-1;
            if (unlikely(val < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned short");
                return (unsigned short)-1;
            }
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return (unsigned short)val;
    }
    return (unsigned short)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE unsigned int __Pyx_PyInt_AsUnsignedInt(PyObject* x) {
    if (sizeof(unsigned int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned int)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (unsigned int)-1;
            if (unlikely(val < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned int");
                return (unsigned int)-1;
            }
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to unsigned int");
            return (unsigned int)-1;
        }
        return (unsigned int)val;
    }
    return (unsigned int)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE char __Pyx_PyInt_AsChar(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(char)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (char)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to char");
            return (char)-1;
        }
        return (char)val;
    }
    return (char)__Pyx_PyInt_AsLong(x);
}

static INLINE short __Pyx_PyInt_AsShort(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(short)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (short)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to short");
            return (short)-1;
        }
        return (short)val;
    }
    return (short)__Pyx_PyInt_AsLong(x);
}

static INLINE int __Pyx_PyInt_AsInt(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(int)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (int)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to int");
            return (int)-1;
        }
        return (int)val;
    }
    return (int)__Pyx_PyInt_AsLong(x);
}

static INLINE signed char __Pyx_PyInt_AsSignedChar(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed char)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (signed char)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to signed char");
            return (signed char)-1;
        }
        return (signed char)val;
    }
    return (signed char)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE signed short __Pyx_PyInt_AsSignedShort(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed short)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (signed short)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to signed short");
            return (signed short)-1;
        }
        return (signed short)val;
    }
    return (signed short)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE signed int __Pyx_PyInt_AsSignedInt(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed int)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (signed int)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to signed int");
            return (signed int)-1;
        }
        return (signed int)val;
    }
    return (signed int)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE unsigned long __Pyx_PyInt_AsUnsignedLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned long");
            return (unsigned long)-1;
        }
        return (unsigned long)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        if (unlikely(Py_SIZE(x) < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned long");
            return (unsigned long)-1;
        }
        return PyLong_AsUnsignedLong(x);
    } else {
        unsigned long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (unsigned long)-1;
        val = __Pyx_PyInt_AsUnsignedLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __Pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned PY_LONG_LONG");
            return (unsigned PY_LONG_LONG)-1;
        }
        return (unsigned PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        if (unlikely(Py_SIZE(x) < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned PY_LONG_LONG");
            return (unsigned PY_LONG_LONG)-1;
        }
        return PyLong_AsUnsignedLongLong(x);
    } else {
        unsigned PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (unsigned PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE long __Pyx_PyInt_AsLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        return (long)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        return PyLong_AsLong(x);
    } else {
        long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (long)-1;
        val = __Pyx_PyInt_AsLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE PY_LONG_LONG __Pyx_PyInt_AsLongLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        return (PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        return PyLong_AsLongLong(x);
    } else {
        PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE signed long __Pyx_PyInt_AsSignedLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        return (signed long)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        return PyLong_AsLong(x);
    } else {
        signed long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (signed long)-1;
        val = __Pyx_PyInt_AsSignedLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE signed PY_LONG_LONG __Pyx_PyInt_AsSignedLongLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        return (signed PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        return PyLong_AsLongLong(x);
    } else {
        signed PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (signed PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsSignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    #if PY_MAJOR_VERSION < 3
    empty_string = PyString_FromStringAndSize("", 0);
    #else
    empty_string = PyBytes_FromStringAndSize("", 0);
    #endif
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_GET(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode && (!t->is_identifier)) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_identifier || (t->is_unicode && t->intern)) {
            *t->p = PyUnicode_InternFromString(t->s);
        } else if (t->is_unicode) {
            *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if ((x == Py_False) | (x == Py_None)) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PyObject* __Pyx_PyNumber_Int(PyObject* x) {
  PyNumberMethods *m;
  const char *name = NULL;
  PyObject *res = NULL;
#if PY_VERSION_HEX < 0x03000000
  if (PyInt_Check(x) || PyLong_Check(x))
#else
  if (PyLong_Check(x))
#endif
    return Py_INCREF(x), x;
  m = Py_TYPE(x)->tp_as_number;
#if PY_VERSION_HEX < 0x03000000
  if (m && m->nb_int) {
    name = "int";
    res = PyNumber_Int(x);
  }
  else if (m && m->nb_long) {
    name = "long";
    res = PyNumber_Long(x);
  }
#else
  if (m && m->nb_int) {
    name = "int";
    res = PyNumber_Long(x);
  }
#endif
  if (res) {
#if PY_VERSION_HEX < 0x03000000
    if (!PyInt_Check(res) && !PyLong_Check(res)) {
#else
    if (!PyLong_Check(res)) {
#endif
      PyErr_Format(PyExc_TypeError,
                   "__%s__ returned non-%s (type %.200s)",
                   name, name, Py_TYPE(res)->tp_name);
      Py_DECREF(res);
      return NULL;
    }
  }
  else if (!PyErr_Occurred()) {
    PyErr_SetString(PyExc_TypeError,
                    "an integer is required");
  }
  return res;
}

static INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t ival) {
#if PY_VERSION_HEX < 0x02050000
   if (ival <= LONG_MAX)
       return PyInt_FromLong((long)ival);
   else {
       unsigned char *bytes = (unsigned char *) &ival;
       int one = 1; int little = (int)*(unsigned char*)&one;
       return _PyLong_FromByteArray(bytes, sizeof(size_t), little, 0);
   }
#else
   return PyInt_FromSize_t(ival);
#endif
}

static INLINE size_t __Pyx_PyInt_AsSize_t(PyObject* x) {
   unsigned PY_LONG_LONG val = __Pyx_PyInt_AsUnsignedLongLong(x);
   if (unlikely(val == (unsigned PY_LONG_LONG)-1 && PyErr_Occurred())) {
       return (size_t)-1;
   } else if (unlikely(val != (unsigned PY_LONG_LONG)(size_t)val)) {
       PyErr_SetString(PyExc_OverflowError,
                       "value too large to convert to size_t");
       return (size_t)-1;
   }
   return (size_t)val;
}


